package com.routee.qianbaotest.utils;

/**
 * Created by Routee on 2017/11/29.
 */

public class ArithmeticTest {
    /*Problem 1
    If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

    Find the sum of all the multiples of 3 or 5 below 1000.*/
    public static int multiplesOf3And5(int count) {
        int sum = 0;
        for (int i = 1; i < count; i++) {
            if (i % 3 == 0) {
                sum += i;
                continue;
            }
            if (i % 5 == 0) {
                sum += i;
                continue;
            }
        }
        return sum;
    }

    /*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

            1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/
    public static int EvenFibonacciNumbers(int count) {
        int sum = 0;
        int i1 = 1;
        int i2 = 2;
        while (i2 < count) {
            int n = i2;
            if (i2 % 2 == 0) {
                sum += i2;
            }
            i2 = i1 + i2;
            i1 = n + 0;
        }
        return sum;
    }

    /*Largest prime factor
    Problem 3
    The prime factors of 13195 are 5, 7, 13 and 29.

    What is the largest prime factor of the number 600851475143 ?*/
    public static long largestPrimeFactor(long count) {
        long max = 0;
        for (long i = 2; i <= count; i++) {
            if (count % i == 0) {
                count /= i;
                max = max > i ? max : i;
                if (count == i) {
                    return max;
                }
                i = 1;
            }
        }
        return max;
    }
}
